matrix:
- name: python
  sources:
  - parmoo/**/*.py
  - examples/**/*.py
  - docs/**/*.rst  
  - "*.rst"
  - "*.py"
  aspell:
    lang: en
    d: en_US
  pipeline:
  - pyspelling.filters.python:
      strings: false
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: "(?<=\w\'"
      - close: "\\b"
  dictionary:
    wordlists:
    - .github/config/custom-wordlist.txt
