matrix:
- name: python
  sources:
  - parmoo/**/*.py
  - examples/**/*.py
  - "*.py"
  aspell:
    lang: en
    d: en_US
  pipeline:
  - pyspelling.filters.python:
      strings: false
  dictionary:
    wordlists:
    - .github/config/custom-wordlist.txt
- name: rst
  sources:
  - docs/**/*.rst  
  - "*.rst"
  aspell:
    lang: en
    d: en_US
  pipeline:
  - pyspelling.filters.context:
      context_visible_first: true
      # There is no filter for .rst, so we write some custom filters below
      delimiters:
      # Ignore code blocks
      - open: "```"
        close: "```"
      - open: "``"
        close: "``"
      - open: "`"
        close: "`"
      - open: "^\\s"
        close: "\\n"
      # Ignore et al.
      - open: "\\<et\\>"
        close: "\\<al\\.\\>"
      # Ignore all rst primitives beginning with ".."
      - open: "\\.\\.\\s+:[a-zA-Z\\-_0-9]+"
        close: "\\n"
      - open: "\\.\\.\\s+[a-zA-Z\\-_0-9]+:"
        close: "\\n"
      # Ignore all rst primitives beginning with ":"
      - open: "\\s+:[a-zA-Z\\-_0-9]+:"
        close: "\\n"
      # Ignore all URLs
      - open: "http|www"
        close: "\\b"
  dictionary:
    wordlists:
    - .github/config/custom-wordlist.txt
