name: Spellcheck RST files

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pyspelling
        run: pip install pyspelling

      - name: Spellcheck RST files
        run: |
          pyspelling -c .github/workflows/.spellcheckconfig.yml 

      - name: Upload spellcheck report
        uses: actions/upload-artifact@v2
        with:
          name: spellcheck-report
          path: spellcheck-report.txt
